# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config user.email "mdkher@gmail.com"
    - run: git config user.name "Manan Kher"
    - run: npm install
    - run: npm install -g angular-cli-ghpages
    - run: npm run-script build
    - run: angular-cli-ghpages --repo=https://f183c4bf141ecfd3e6ecab8568ccc5fcc12953e1@github.com/mdkher/personal-portfolio.git
